[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/audit"
  to = "/audit.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.netlify.app *.google.com *.googleusercontent.com *.facebook.com https://cdn.tailwindcss.com; connect-src 'self' *.google.com *.googleusercontent.com *.supabase.co wss://*.supabase.co"
